### ISSUE TITLE
do not generate for private classes

### ISSUE THREAD

**Issue by ignatandrei** [byme8/Apparatus.AOT.Reflection#1]
If you have a class 
```csharp
partial class Person
{
    [Required]
    public string FirstName { get; set; }
    public string LastName { get; set; }
}
```

then compiling gives the error:

error CS0051: Inconsistent accessibility: parameter type 'Person' is less accessible than method 'CopyConstructor_PersonExtensions.GetProperties(Person)'
1>Done building project "ApparatusAOT.csproj" -- FAILED

**Comment by byme8** [comment]
Thanks! I will check it.

**Comment by byme8** [comment]
I have pushed the fix. You can test it with Apparatus.AOT.Reflection v0.2.0. Also now it has support for enums.

**Comment by ignatandrei** [comment]
It works now. Mentioned at my list of RSCG at https://github.com/ignatandrei/RSCG_Examples/tree/main/ApparatusAOT
