### ISSUE TITLE
A question about the library

### ISSUE THREAD

**Issue by yoav-melamed** [byme8/Apparatus.AOT.Reflection#5]
Hi there,
Can I use this library for dynamically loading assemblies (like plugins) at the runtime like I currently do with reflection?
Today I'm using reflection to:
- load an assembly at runtime
- unload an assembly at runtime
- execute methods in the loaded assembly

Thank you for your work! You've already got my star :)

**Comment by byme8** [comment]
Not, you can not. This library is more about optimizing access to type metadata available during the compilation time. Using plugins is more about loading something you don't know about during the compilation.
